spring.application.name=smart-campus-backend
spring.data.mongodb.host=mongo
spring.data.mongodb.port=27017
spring.data.mongodb.database=smartcampus
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
server.port=8080
face-service.base-url=http://face-service:8000
logging.level.com.smartcampus.backend=INFO
